# Chapter 02
## Input Output

In [2]:
import numpy as np
import cv2
import pandas as pd

In [9]:
img=np.zeros((3,3), dtype=np.uint8)  #unsugned 8 bit integer uint8
print(img)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
img=cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
print(img)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [11]:
img=cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
print(img)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [12]:
img=np.zeros((3,5),dtype=np.uint8)
np.shape(img)
print(img.shape)

(3, 5)


In [13]:
img=cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
np.shape(img)
print(img.shape)

(3, 5, 3)
